# Generated by Django 6.0.4 on 2026-06-30 07:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('founder', 'Founder'), ('cofounder', 'Co-Founder'), ('developer', 'Developer'), ('designer', 'Designer'), ('product_manager', 'Product Manager'), ('marketer', 'Marketing Specialist'), ('sales', 'Sales'), ('devops', 'DevOps'), ('qa', 'QA Engineer'), ('advisor', 'Advisor'), ('mentor', 'Mentor')], max_length=30)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='startups.startup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('startup', 'user'), name='unique_member')],
            },
        ),
    ]
