# Generated by Django 6.0.4 on 2026-06-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_startupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='is_open_source',
            field=models.BooleanField(default=False),
        ),
    ]
